spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html